// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiSwagger.Context;

#nullable disable

namespace WebApiSwagger.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240724202008_Agf_mysql")]
    partial class Agf_mysql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Diretorio", b =>
                {
                    b.Property<int>("Id_Diretorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Caminho")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Diretorio");

                    b.ToTable("Diretorios");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Analise", b =>
                {
                    b.Property<int>("Id_Analise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnaliseObservacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Analista")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_TesteOptico")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Analise");

                    b.HasIndex("Id_TesteOptico");

                    b.ToTable("Analises");
                });

            modelBuilder.Entity("WebApiSwagger.Models.AnaliseCDOIA", b =>
                {
                    b.Property<int>("Id_AnaliseCDOIA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Analista")
                        .HasColumnType("longtext");

                    b.Property<string>("CDOIA")
                        .HasColumnType("longtext");

                    b.Property<string>("CDOIAObservacao")
                        .HasColumnType("longtext");

                    b.Property<string>("CDOIAStatus")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAnalise")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_TesteOptico")
                        .HasColumnType("int");

                    b.HasKey("Id_AnaliseCDOIA");

                    b.HasIndex("Id_TesteOptico");

                    b.ToTable("AnaliseCDOIAs");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Cargo", b =>
                {
                    b.Property<int>("Id_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Cargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Empresa", b =>
                {
                    b.Property<int>("Id_Empresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Empresa");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("WebApiSwagger.Models.EnderecoTotal", b =>
                {
                    b.Property<int>("Id_EnderecoTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnoMes")
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .HasColumnType("longtext");

                    b.Property<string>("Celula")
                        .HasColumnType("longtext");

                    b.Property<string>("ChaveCelula")
                        .HasColumnType("longtext");

                    b.Property<string>("Cod_Localidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Cod_Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cod_Survey")
                        .HasColumnType("longtext");

                    b.Property<string>("Cod_Viabilidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Complemento")
                        .HasColumnType("longtext");

                    b.Property<string>("ComplementoDois")
                        .HasColumnType("longtext");

                    b.Property<string>("ComplementoTres")
                        .HasColumnType("longtext");

                    b.Property<string>("DataAssociacao")
                        .HasColumnType("longtext");

                    b.Property<string>("DataEstadoControle")
                        .HasColumnType("longtext");

                    b.Property<string>("Disp_Comercial")
                        .HasColumnType("longtext");

                    b.Property<string>("Disponibilidade")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoControle")
                        .HasColumnType("longtext");

                    b.Property<string>("Id_Associacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Id_Celula")
                        .HasColumnType("longtext");

                    b.Property<int>("Id_Disponibilidade")
                        .HasColumnType("int");

                    b.Property<string>("Id_Endereco")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_MaterialRede")
                        .HasColumnType("int");

                    b.Property<int>("Id_StatusGanho")
                        .HasColumnType("int");

                    b.Property<string>("Latitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Localidade")
                        .HasColumnType("longtext");

                    b.Property<string>("LocalidadeAbrev")
                        .HasColumnType("longtext");

                    b.Property<string>("Logradouro")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCdo")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroFachada")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroPiso")
                        .HasColumnType("longtext");

                    b.Property<string>("Projeto")
                        .HasColumnType("longtext");

                    b.Property<int?>("QuantidadeUMS")
                        .HasColumnType("int");

                    b.Property<string>("Quantidade_HCS")
                        .HasColumnType("longtext");

                    b.Property<string>("RedeEdificio_Certificados")
                        .HasColumnType("longtext");

                    b.Property<string>("RedeInterna")
                        .HasColumnType("longtext");

                    b.Property<string>("SiglaEstacao")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusGanho")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoRede")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSurvey")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoViabilidade")
                        .HasColumnType("longtext");

                    b.Property<string>("UCS_Comerciais")
                        .HasColumnType("longtext");

                    b.Property<string>("UCS_Residenciais")
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.Property<string>("UMS_Certificadas")
                        .HasColumnType("longtext");

                    b.HasKey("Id_EnderecoTotal");

                    b.HasIndex("Id_MaterialRede");

                    b.ToTable("EnderecosTotais");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Info", b =>
                {
                    b.Property<int>("Id_info")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Atualizar")
                        .HasColumnType("int");

                    b.Property<string>("Base")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataImport")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_info");

                    b.ToTable("Infos");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Ligacao", b =>
                {
                    b.Property<int>("Id_Ligacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BSP_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("CDO_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("CaboCdo_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("CaboDgo_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("CaboPrimario_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("CaboSecundario_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Celula_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("DGO_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Destinacao_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCicloVida_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("EtiquetaCampo_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("EtiquetaPadrao_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("EtiquetaTerceiro_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("FibraCdo_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("FibraDgo_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("ForaPadrao_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("ICX_ls")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_MaterialRede")
                        .HasColumnType("int");

                    b.Property<string>("IdentificacaoTerceiro_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Infraestrutura_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Localidade_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeOlt_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("OutSplitterCEOS_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("PortaCdo_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("PortaOlt_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Projeto_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("Rede_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("SPLITTER_CDO")
                        .HasColumnType("longtext");

                    b.Property<string>("SiglaEstacao_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("SplitterCEOS_ls")
                        .HasColumnType("longtext");

                    b.Property<string>("UF_ls")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Ligacao");

                    b.HasIndex("Id_MaterialRede");

                    b.ToTable("Ligacoes");
                });

            modelBuilder.Entity("WebApiSwagger.Models.MaisDeUmaCDO", b =>
                {
                    b.Property<int>("Id_MaisDeUmaCDO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Associacao_CDO")
                        .HasColumnType("longtext");

                    b.Property<string>("Celula_Mc")
                        .HasColumnType("longtext");

                    b.Property<string>("ChaveCelula")
                        .HasColumnType("longtext");

                    b.Property<string>("Data_de_associacao")
                        .HasColumnType("longtext");

                    b.Property<int>("EnderecosTotaisId_EnderecoTotal")
                        .HasColumnType("int");

                    b.Property<string>("Estacao_Mc")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_EnderecoTotal")
                        .HasColumnType("int");

                    b.Property<string>("Nome_CDO")
                        .HasColumnType("longtext");

                    b.Property<string>("Survey_Mc")
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.HasKey("Id_MaisDeUmaCDO");

                    b.HasIndex("EnderecosTotaisId_EnderecoTotal");

                    b.ToTable("MaisDeUmaCDOs");
                });

            modelBuilder.Entity("WebApiSwagger.Models.MaterialRede", b =>
                {
                    b.Property<int>("Id_MaterialRede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CHAVE")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoSap_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Codigo_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("DataEstadoControle_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("DataEstadoOperacional_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("ElementoRede_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoControle_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoOperacional_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Fabricante_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoOperacional_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("InfraestruturaRede_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Latitude_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Longitude_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Modelo_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeAbastecedora_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeFederativa_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeLocalidade_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("SiglaAbastecedora_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("SiglaFederativa_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("SiglaLocalidade_Mt")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo_Mt")
                        .HasColumnType("longtext");

                    b.HasKey("Id_MaterialRede");

                    b.ToTable("MateriaisRedes");
                });

            modelBuilder.Entity("WebApiSwagger.Models.ServicoAssociado", b =>
                {
                    b.Property<int>("Id_ServicoAssociados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CFSAcessoGPON")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoSurvey")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoAcessoGPON")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoHSI")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoProvPortaFisica")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_EnderecoTotal")
                        .HasColumnType("int");

                    b.HasKey("Id_ServicoAssociados");

                    b.HasIndex("Id_EnderecoTotal");

                    b.ToTable("ServicoAssociados");
                });

            modelBuilder.Entity("WebApiSwagger.Models.StatusAnalise", b =>
                {
                    b.Property<int>("Id_StatusAnalise")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_StatusAnalise");

                    b.ToTable("StatusAnalises");
                });

            modelBuilder.Entity("WebApiSwagger.Models.StatusControle", b =>
                {
                    b.Property<int>("Id_StatusControle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_StatusControle");

                    b.ToTable("StatusControles");
                });

            modelBuilder.Entity("WebApiSwagger.Models.StatusLogin", b =>
                {
                    b.Property<int>("Id_StatusLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LoginDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id_StatusLogin");

                    b.HasIndex("Id_Usuario")
                        .IsUnique();

                    b.ToTable("StatusLogins");
                });

            modelBuilder.Entity("WebApiSwagger.Models.StatusNetwin", b =>
                {
                    b.Property<int>("Id_StatusNetwin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id_StatusNetwin");

                    b.ToTable("StatusNetwins");
                });

            modelBuilder.Entity("WebApiSwagger.Models.StatusProjeto", b =>
                {
                    b.Property<int>("Id_StatusProjeto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_StatusProjeto");

                    b.ToTable("StatusProjetos");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Tecnico", b =>
                {
                    b.Property<int>("Id_Tecnico")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_Cargo")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Empresa")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Tecnico");

                    b.HasIndex("Id_Cargo");

                    b.HasIndex("Id_Empresa");

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("WebApiSwagger.Models.TesteOptico", b =>
                {
                    b.Property<int>("Id_TesteOptico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("AceitacaoData")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("AceitacaoMesRef")
                        .HasColumnType("longtext");

                    b.Property<string>("BobinaLancamento")
                        .HasColumnType("longtext");

                    b.Property<string>("BobinaRecepcao")
                        .HasColumnType("longtext");

                    b.Property<string>("CDO")
                        .HasColumnType("longtext");

                    b.Property<string>("CHAVE")
                        .HasColumnType("longtext");

                    b.Property<string>("Cabo")
                        .HasColumnType("longtext");

                    b.Property<string>("Capacidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Celula")
                        .HasColumnType("longtext");

                    b.Property<string>("Construtora")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataConstrucao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataRecebimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataTeste")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("EquipeConstrucao")
                        .HasColumnType("longtext");

                    b.Property<string>("Estacao")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCampo")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoControle")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoProjeto")
                        .HasColumnType("longtext");

                    b.Property<string>("FibraDGO")
                        .HasColumnType("longtext");

                    b.Property<int?>("Id_MaterialRede")
                        .HasColumnType("int");

                    b.Property<string>("Meta")
                        .HasColumnType("longtext");

                    b.Property<string>("PosicaoIcxDgo")
                        .HasColumnType("longtext");

                    b.Property<string>("QuantidadeTeste")
                        .HasColumnType("longtext");

                    b.Property<int?>("Sel")
                        .HasColumnType("int");

                    b.Property<string>("SiglaEstacao")
                        .HasColumnType("longtext");

                    b.Property<string>("SplitterCEOS")
                        .HasColumnType("longtext");

                    b.Property<string>("Tecnico")
                        .HasColumnType("longtext");

                    b.Property<string>("TesteObservacao")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoObra")
                        .HasColumnType("longtext");

                    b.Property<int?>("TotalUMs")
                        .HasColumnType("int");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.Property<string>("Viabilidade")
                        .HasColumnType("longtext");

                    b.HasKey("Id_TesteOptico");

                    b.HasIndex("Id_MaterialRede")
                        .IsUnique();

                    b.ToTable("TestesOpticos");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Error")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .HasColumnType("longtext");

                    b.Property<int?>("Publico")
                        .HasColumnType("int");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<int?>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id_Usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Validacao", b =>
                {
                    b.Property<int>("Id_Validacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataValidacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Id_TesteOptico")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Tecnico")
                        .HasColumnType("longtext");

                    b.HasKey("Id_Validacao");

                    b.HasIndex("Id_TesteOptico");

                    b.ToTable("Validacoes");
                });

            modelBuilder.Entity("WebApiSwagger.Models.ViewModel.EnderecoTotalDropListView", b =>
                {
                    b.Property<int>("Id_DropEnderecosTotais")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AnoMes")
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cod_Viabilidade")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoControle")
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoOperacional")
                        .HasColumnType("longtext");

                    b.Property<string>("GrupoOperacional")
                        .HasColumnType("longtext");

                    b.Property<string>("Municipio")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeAbastecedora")
                        .HasColumnType("longtext");

                    b.Property<string>("SiglaEstacao")
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.HasKey("Id_DropEnderecosTotais");

                    b.ToTable("DropEnderecosTotais");
                });

            modelBuilder.Entity("WebApiSwagger.Models.ViewModel.ViewStatusGanho", b =>
                {
                    b.Property<int?>("Id_Disponibilidade")
                        .HasColumnType("int");

                    b.Property<int?>("Id_StatusGanho")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPorStatus")
                        .HasColumnType("int");

                    b.ToTable("ViewStatusGanhos");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Analise", b =>
                {
                    b.HasOne("WebApiSwagger.Models.TesteOptico", null)
                        .WithMany("Analises")
                        .HasForeignKey("Id_TesteOptico")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiSwagger.Models.AnaliseCDOIA", b =>
                {
                    b.HasOne("WebApiSwagger.Models.TesteOptico", null)
                        .WithMany("AnaliseCDOIAs")
                        .HasForeignKey("Id_TesteOptico")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiSwagger.Models.EnderecoTotal", b =>
                {
                    b.HasOne("WebApiSwagger.Models.MaterialRede", "MaterialRede")
                        .WithMany("EnderecoTotal")
                        .HasForeignKey("Id_MaterialRede");

                    b.Navigation("MaterialRede");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Ligacao", b =>
                {
                    b.HasOne("WebApiSwagger.Models.MaterialRede", "MaterialRede")
                        .WithMany("Ligacao")
                        .HasForeignKey("Id_MaterialRede");

                    b.Navigation("MaterialRede");
                });

            modelBuilder.Entity("WebApiSwagger.Models.MaisDeUmaCDO", b =>
                {
                    b.HasOne("WebApiSwagger.Models.EnderecoTotal", "EnderecosTotais")
                        .WithMany()
                        .HasForeignKey("EnderecosTotaisId_EnderecoTotal")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnderecosTotais");
                });

            modelBuilder.Entity("WebApiSwagger.Models.ServicoAssociado", b =>
                {
                    b.HasOne("WebApiSwagger.Models.EnderecoTotal", "EnderecosTotais")
                        .WithMany("ServicosAssociados")
                        .HasForeignKey("Id_EnderecoTotal");

                    b.Navigation("EnderecosTotais");
                });

            modelBuilder.Entity("WebApiSwagger.Models.StatusLogin", b =>
                {
                    b.HasOne("WebApiSwagger.Models.Usuario", null)
                        .WithOne("StatusLogin")
                        .HasForeignKey("WebApiSwagger.Models.StatusLogin", "Id_Usuario");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Tecnico", b =>
                {
                    b.HasOne("WebApiSwagger.Models.Cargo", "GetCargo")
                        .WithMany()
                        .HasForeignKey("Id_Cargo");

                    b.HasOne("WebApiSwagger.Models.Empresa", "GetEmpresa")
                        .WithMany()
                        .HasForeignKey("Id_Empresa");

                    b.HasOne("WebApiSwagger.Models.Usuario", null)
                        .WithOne("GetTecnico")
                        .HasForeignKey("WebApiSwagger.Models.Tecnico", "Id_Tecnico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GetCargo");

                    b.Navigation("GetEmpresa");
                });

            modelBuilder.Entity("WebApiSwagger.Models.TesteOptico", b =>
                {
                    b.HasOne("WebApiSwagger.Models.MaterialRede", "MaterialRede")
                        .WithOne()
                        .HasForeignKey("WebApiSwagger.Models.TesteOptico", "Id_MaterialRede");

                    b.Navigation("MaterialRede");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Validacao", b =>
                {
                    b.HasOne("WebApiSwagger.Models.TesteOptico", null)
                        .WithMany("Validacoes")
                        .HasForeignKey("Id_TesteOptico")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApiSwagger.Models.EnderecoTotal", b =>
                {
                    b.Navigation("ServicosAssociados");
                });

            modelBuilder.Entity("WebApiSwagger.Models.MaterialRede", b =>
                {
                    b.Navigation("EnderecoTotal");

                    b.Navigation("Ligacao");
                });

            modelBuilder.Entity("WebApiSwagger.Models.TesteOptico", b =>
                {
                    b.Navigation("AnaliseCDOIAs");

                    b.Navigation("Analises");

                    b.Navigation("Validacoes");
                });

            modelBuilder.Entity("WebApiSwagger.Models.Usuario", b =>
                {
                    b.Navigation("GetTecnico")
                        .IsRequired();

                    b.Navigation("StatusLogin")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
